version: "3.9"
 
services:
  db:
    image: postgres:17
    container_name: todo_postgres
    restart: always
    environment:
      POSTGRES_USER: noel
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
 
  postgrest:
    image: postgrest/postgrest:v13.0.4
    container_name: my_postgrest
    restart: always
    depends_on:
      - db
    environment:
      PGRST_DB_URI: postgres://noel:1234@db:5432/todo_db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: noel
    ports:
      - "3000:3000"
 
volumes:
  db_data: